---
  - name: Install unzip
    package:
      name: unzip
      update_cache: yes
    become: true

  - name: Download and install vault binary
    unarchive:
      src: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
      dest: /usr/bin/
      remote_src: yes
    become: true

  - name: Create vault config directory
    file: 
      path: /etc/vault/
      state: directory 
    become: true

  - name: Copy vault config to server
    copy: 
      src: config.hcl.j2 
      dest: /etc/vault/config.hcl
    become: true

  - name: Copy vault service to server
    copy: 
      src: vault.service.j2
      dest: /usr/lib/systemd/system/vault.service
    become: true

  - name: Start vault service
    systemd:
      state: started
      name: vault
      daemon_reload: yes
    become: true

  - pause:
      seconds: 15

  - name: Initialize the vault
    command: vault operator init
    register: vault_keys
    environment:
      VAULT_ADDR: "http://{{ vault_server_Address }}:8200"

  - debug: msg="{{ vault_keys }}"
